spring.application.name=AIOllamaDepspeek


spring.ai.ollama.chat.options.model=deepseek-r1:7b


telegram.bot.username=al_qa_bot
telegram.bot.token=7962934736:AAHGl6_Dz2lNfqoRQD7I0t6k06Pe90xeWDw


spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/botaifull
spring.datasource.username=postgres
spring.datasource.password=02050

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

telegram.webapp.url=https://lucent-bavarois-649ea1.netlify.app/
